language: python
python: "3.5"
install:
  pip install colored
  pip install coveralls
  #pip install python-coveralls
  #pip install coverage   #add me to install coverage.py
  #pip install nose     #add me to install nose
script:
  #python setup.py install
  make test
  coverage run --source=mypkg rpn.py test
  #nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  coveralls
